In [1]:
import numpy as np
import pandas as pd

In [2]:
R = pd.read_excel("R matrix.xlsx",header=None)

In [3]:
R = np.matrix(R)
R

matrix([[ -1,  -1,  -1,   0,  -1,  -1,  -1,  -1,  -1,  -1],
        [ -1,  -1,   0,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
        [ -1,   0,  -1,  -1,  -1,   0,  -1,  -1,  -1, 100],
        [  0,  -1,  -1,  -1,   0,  -1,   0,  -1,  -1,  -1],
        [ -1,  -1,  -1,   0,  -1,   0,  -1,   0,  -1,  -1],
        [ -1,  -1,   0,  -1,   0,  -1,  -1,  -1,  -1,  -1],
        [ -1,  -1,  -1,   0,  -1,  -1,  -1,  -1,  -1,  -1],
        [ -1,  -1,  -1,  -1,   0,  -1,  -1,  -1,   0, 100],
        [ -1,  -1,  -1,  -1,  -1,  -1,  -1,   0,  -1,  -1],
        [ -1,  -1,   0,  -1,  -1,  -1,  -1,   0,  -1, 100]])

In [30]:
# intialize Q matrix
Q = np.zeros([10,10])

In [5]:
# setting gamma parameter
gamma = 0.7

In [6]:
#intialize state for the mouse(We will later make this selection random)
intial_state = 2

In [9]:
# find available actions
def avl_action(state):
  current_state_row=R[state,]
  av_act=np.where(current_state_row>=0)[1]
  return av_act


In [15]:
# get the available actions in current state = 2
available_actions= avl_action(intial_state)
available_actions

array([1, 5, 9])

In [16]:
# Selecting random choice from available actions
def sample_mext_action(available_actions_range):
  next_action = int(np.random.choice(available_actions_range,1))
  return next_action


In [20]:
action = sample_mext_action(available_actions)
action

9

In [25]:
# updating the Q matrix Q[s, a] = R[s, a] +  gamma*Max[Q[s, a])
def update(current_state,action,gamma):
  max_index = np.where(Q[action,] == np.max(Q[action,]))[0]
  if max_index.shape[0]>1:
    max_index = int(np.random.choice(max_index,1))
  else:
    max_index = int(max_index)
  max_value = Q[action,max_index]
  Q[current_state,action] = R[current_state,action] + gamma*max_value

In [26]:
update(intial_state,action,gamma)
Q

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 100.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [40]:
# Training the Q matrix
Q = np.zeros([10,10])
for i in range(10000):
  intial_state = np.random.randint(Q.shape[0])
  available_actions = avl_action(intial_state)
  action = sample_mext_action(available_actions)
  gamma = 0.8
  update(intial_state,action,gamma)

In [41]:
Q

array([[  0. ,   0. ,   0. , 256. ,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ],
       [  0. ,   0. , 400. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ],
       [  0. , 320. ,   0. ,   0. ,   0. , 320. ,   0. ,   0. ,   0. ,
        500. ],
       [204.8,   0. ,   0. ,   0. , 320. ,   0. , 204.8,   0. ,   0. ,
          0. ],
       [  0. ,   0. ,   0. , 256. ,   0. , 320. ,   0. , 400. ,   0. ,
          0. ],
       [  0. ,   0. , 400. ,   0. , 320. ,   0. ,   0. ,   0. ,   0. ,
          0. ],
       [  0. ,   0. ,   0. , 256. ,   0. ,   0. ,   0. ,   0. ,   0. ,
          0. ],
       [  0. ,   0. ,   0. ,   0. , 320. ,   0. ,   0. ,   0. , 320. ,
        500. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. , 400. ,   0. ,
          0. ],
       [  0. ,   0. , 400. ,   0. ,   0. ,   0. ,   0. , 400. ,   0. ,
        500. ]])

In [52]:
current_state = 5
steps = [current_state]
while current_state != 9:
  next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[0]
  if next_step_index.shape[0]>1:
    next_step_index = int(np.random.choice(next_step_index,1))
  else:
    next_step_index = int(next_step_index)
  steps.append(next_step_index)
  current_state = next_step_index

print("The ideal path is: ", str(steps)[1:-1])
   

  


The ideal path is:  5, 2, 9
