In [1]:
import numpy as np
import pandas as pd

In [2]:
# Create the State Action Reward Matrix

R = pd.read_excel('Square Matrix.xlsx',header=None)

In [3]:
R = np.matrix(R)
R

matrix([[ -1,   0,  -1, ...,  -1,  -1,  -1],
        [ -1,  -1,  -1, ...,  -1,  -1,  -1],
        [ -1,  -1,  -1, ...,  -1,  -1,  -1],
        ...,
        [ -1,  -1,  -1, ...,  -1,  -1, 100],
        [ -1,  -1,  -1, ...,  -1,  -1,  -1],
        [ -1,  -1,  -1, ...,   0,  -1,  -1]])

In [4]:
# Initialize the Q matrix with zeros

Q = np.zeros([39,39])

In [5]:
Q

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
# Set Gamma parameter

gamma = 0.7

In [10]:
# Initialize state for the mouse ( We will later make this selection random)

initial_state = 0

In [11]:
# Create a custom function that returns all available actions in the state passed as an argument

def avl_actions(state):
  current_state_row = R[state,]
  av_act = np.where(current_state_row >= 0)[1]
  return av_act

In [13]:
np.where(R[0,] >= 0)[1]

array([1])

In [14]:
# Get the available actions in current state = 2

available_act = avl_actions(initial_state)

In [15]:
available_act

array([1])

In [16]:
# Next , we construct a function which chooses a random action to be performed within the range of all avl actions


def sample_next_action(available_actions_range):
  next_action = int(np.random.choice(available_actions_range,1))
  return next_action

In [17]:
action = sample_next_action(available_act)
action

1

In [18]:
# Now, we update the Q matrix according to the path selected using the Q learning algorithm formula

def update(current_state,action,gamma):
  max_index = np.where(Q[action,] == np.max(Q[action,]))[0]

  if max_index.shape[0] > 1:
    max_index = int(np.random.choice(max_index,1))

  else:
    max_index = int(max_index)

  max_value = Q[action,max_index]

  # Q-learning formula
  Q[current_state,action] = R[current_state,action] + gamma*max_value

In [19]:
# Update the Q matrix
update(initial_state,action,gamma)

In [ ]:
Q

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
# Training Q - Matrix

for i in range(100000):
  current_state = np.random.randint(0,39)
  available_actions = avl_actions(current_state)
  action = sample_next_action(available_actions)
  update(current_state,action,gamma)

In [22]:
Q.shape[0]

39

In [32]:
current_state = 0
steps = [current_state]

while current_state != 38:
  next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[0]

  if next_step_index.shape[0] > 1:
    next_step_index = int(np.random.choice(next_step_index, 1))

  else:
    next_step_index = int(next_step_index)

  steps.append(next_step_index)
  current_state = next_step_index


print("The selected path:")
print(steps)

The selected path:
[0, 1, 7, 12, 6, 4, 5, 11, 16, 21, 24, 28, 32, 36, 38]
